<?php

namespace Database\Seeders;

use App\Models\BabySizeComparison;
use Illuminate\Database\Seeder;

class BabySizeComparisonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Seeding baby size comparisons...');

        $data = [
            // Week 1–4 (Microscopic)
            [
                'week' => '1',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 0.1,
                'weight' => 0.0,
                'milestone_remarks' => 'Fertilization occurs. The zygote begins cell division and travels down the fallopian tube. This is the very beginning of your baby\'s journey.',
            ],
            [
                'week' => '2',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 0.2,
                'weight' => 0.0,
                'milestone_remarks' => 'The blastocyst implants into the uterine wall. Cell division continues rapidly, and the foundation for all major organs begins to form.',
            ],
            [
                'week' => '3',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 0.3,
                'weight' => 0.0,
                'milestone_remarks' => 'The neural tube begins to form, which will become the brain and spinal cord. The heart starts to develop and may begin beating.',
            ],
            [
                'week' => '4',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 0.4,
                'weight' => 0.0,
                'milestone_remarks' => 'The embryo is now visible. The heart is beating, and the basic structure of the brain, spinal cord, and digestive system is forming.',
            ],
            // Week 5–8
            [
                'week' => '5',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 0.5,
                'weight' => 0.5,
                'milestone_remarks' => 'The heart is beating regularly. Arm and leg buds appear, and the brain continues to develop rapidly. Facial features begin to form.',
            ],
            [
                'week' => '6',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 0.6,
                'weight' => 1.0,
                'milestone_remarks' => 'The heart rate increases. Eyes, ears, and nose begin to take shape. The neural tube closes, and the brain continues developing.',
            ],
            [
                'week' => '7',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 1.0,
                'weight' => 2.0,
                'milestone_remarks' => 'Arms and legs are growing. Fingers and toes begin to form. The liver, kidneys, and intestines are developing. Baby is now moving, though you can\'t feel it yet.',
            ],
            [
                'week' => '8',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 1.6,
                'weight' => 3.0,
                'milestone_remarks' => 'All major organs have begun to form. The embryo is now called a fetus. Fingers and toes are becoming more distinct. The tail disappears.',
            ],
            // Week 9–12
            [
                'week' => '9',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 2.3,
                'weight' => 5.0,
                'milestone_remarks' => 'The baby\'s head is more rounded, and facial features are becoming more human-like. The baby can make a fist and may start sucking its thumb.',
            ],
            [
                'week' => '10',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 3.1,
                'weight' => 8.0,
                'milestone_remarks' => 'Vital organs are fully formed and beginning to function. The baby can swallow and kick. Fingernails and toenails start to grow.',
            ],
            [
                'week' => '11',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 4.1,
                'weight' => 12.0,
                'milestone_remarks' => 'The baby is becoming more active, moving arms and legs. The genitals are developing, though it\'s still too early to determine gender on ultrasound.',
            ],
            [
                'week' => '12',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 5.4,
                'weight' => 18.0,
                'milestone_remarks' => 'The first trimester is ending. The baby can make facial expressions. Reflexes are developing, and the baby may respond to touch.',
            ],
            // Week 13–16
            [
                'week' => '13',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 7.4,
                'weight' => 28.0,
                'milestone_remarks' => 'Welcome to the second trimester! The baby\'s vocal cords are developing. The baby can hear sounds from outside the womb.',
            ],
            [
                'week' => '14',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 8.7,
                'weight' => 45.0,
                'milestone_remarks' => 'The baby is growing hair, eyebrows, and eyelashes. The baby can make sucking motions and may start to practice breathing movements.',
            ],
            [
                'week' => '15',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 10.1,
                'weight' => 70.0,
                'milestone_remarks' => 'The baby\'s bones are getting harder. The baby can move all joints and limbs. Taste buds are forming, and the baby may be able to taste what you eat.',
            ],
            [
                'week' => '16',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 11.6,
                'weight' => 100.0,
                'milestone_remarks' => 'The baby\'s heart is pumping about 25 quarts of blood per day. The baby can hear your voice and heartbeat. Gender may be visible on ultrasound.',
            ],
            // Week 17–20
            [
                'week' => '17',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 13.0,
                'weight' => 140.0,
                'milestone_remarks' => 'The baby is developing a unique set of fingerprints. The baby can move eyes behind closed lids and may start to have sleep-wake cycles.',
            ],
            [
                'week' => '18',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 14.2,
                'weight' => 190.0,
                'milestone_remarks' => 'You may start feeling the baby move! The baby can yawn, hiccup, and make facial expressions. The baby\'s hearing is improving.',
            ],
            [
                'week' => '19',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 15.3,
                'weight' => 240.0,
                'milestone_remarks' => 'The baby is covered in vernix, a protective coating. The baby\'s brain is developing specialized areas for smell, taste, hearing, vision, and touch.',
            ],
            [
                'week' => '20',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 16.4,
                'weight' => 300.0,
                'milestone_remarks' => 'Halfway there! The baby is swallowing more, which is good practice for the digestive system. The baby can hear and recognize your voice.',
            ],
            // Week 21–24
            [
                'week' => '21',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 26.7,
                'weight' => 360.0,
                'milestone_remarks' => 'The baby is moving a lot and you can feel those kicks! The baby\'s bone marrow starts making blood cells. Taste buds are fully formed.',
            ],
            [
                'week' => '22',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 27.8,
                'weight' => 430.0,
                'milestone_remarks' => 'The baby\'s senses are developing rapidly. The baby can feel touch and may respond to light. Hair is growing on the head.',
            ],
            [
                'week' => '23',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 28.9,
                'weight' => 500.0,
                'milestone_remarks' => 'The baby can hear loud sounds and may be startled by them. Rapid eye movements begin. The baby practices breathing by inhaling amniotic fluid.',
            ],
            [
                'week' => '24',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 30.0,
                'weight' => 600.0,
                'milestone_remarks' => 'The baby\'s lungs are developing surfactant, which helps them breathe after birth. The baby has a regular sleep schedule and responds to your voice.',
            ],
            // Week 25–28
            [
                'week' => '25',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 34.6,
                'weight' => 660.0,
                'milestone_remarks' => 'The baby can respond to familiar sounds, especially your voice. The baby\'s hands are fully developed and can make a fist. The baby may startle at loud noises.',
            ],
            [
                'week' => '26',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 35.6,
                'weight' => 760.0,
                'milestone_remarks' => 'The baby\'s eyes are opening and closing. The baby can see light filtering through your belly. The baby is practicing breathing movements more regularly.',
            ],
            [
                'week' => '27',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 36.6,
                'weight' => 875.0,
                'milestone_remarks' => 'Welcome to the third trimester! The baby can recognize your voice and may respond to music. The baby\'s brain is very active, and REM sleep occurs.',
            ],
            [
                'week' => '28',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 37.6,
                'weight' => 1005.0,
                'milestone_remarks' => 'The baby can blink and has eyelashes. The baby is gaining weight rapidly. The baby\'s brain is developing billions of neurons. The baby may have hiccups.',
            ],
            // Week 29–32
            [
                'week' => '29',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 38.6,
                'weight' => 1153.0,
                'milestone_remarks' => 'The baby\'s bones are fully developed but still soft. The baby can turn its head toward light. The baby is getting stronger and movements are more noticeable.',
            ],
            [
                'week' => '30',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 39.9,
                'weight' => 1319.0,
                'milestone_remarks' => 'The baby can distinguish between light and dark. The baby\'s brain is growing rapidly. The baby may respond to your touch by moving or kicking.',
            ],
            [
                'week' => '31',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 41.1,
                'weight' => 1502.0,
                'milestone_remarks' => 'The baby is gaining weight quickly. The baby can process information from all five senses. The baby\'s lungs are almost fully mature.',
            ],
            [
                'week' => '32',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 42.4,
                'weight' => 1702.0,
                'milestone_remarks' => 'The baby is practicing breathing, sucking, and swallowing. The baby\'s skin is becoming less wrinkled as fat accumulates. The baby may be head-down in preparation for birth.',
            ],
            // Week 33–36
            [
                'week' => '33',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 43.7,
                'weight' => 1918.0,
                'milestone_remarks' => 'The baby\'s immune system is developing. The baby can detect and respond to light. The baby is getting ready for birth by moving into position.',
            ],
            [
                'week' => '34',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 45.0,
                'weight' => 2146.0,
                'milestone_remarks' => 'The baby\'s central nervous system is maturing. The baby\'s skin is becoming smoother. The baby is practicing breathing movements regularly.',
            ],
            [
                'week' => '35',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 46.2,
                'weight' => 2383.0,
                'milestone_remarks' => 'The baby\'s kidneys are fully developed. The baby is gaining about half a pound per week. The baby\'s hearing is fully developed.',
            ],
            [
                'week' => '36',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 47.4,
                'weight' => 2622.0,
                'milestone_remarks' => 'The baby is considered full-term at the end of this week. The baby\'s lungs are fully mature. The baby is practicing all the skills needed for life outside the womb.',
            ],
            // Week 37–40
            [
                'week' => '37',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 48.6,
                'weight' => 2859.0,
                'milestone_remarks' => 'The baby is now considered early term and ready for birth! The baby\'s brain is still developing rapidly. The baby is gaining weight and getting stronger every day.',
            ],
            [
                'week' => '38',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 49.8,
                'weight' => 3083.0,
                'milestone_remarks' => 'The baby is full-term and ready to be born at any time. The baby\'s organs are fully developed and functioning. The baby is practicing breathing and preparing for delivery.',
            ],
            [
                'week' => '39',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 50.7,
                'weight' => 3288.0,
                'milestone_remarks' => 'The baby is fully developed and ready for birth. The baby continues to gain weight and develop brain connections. Most babies are born between 39-40 weeks.',
            ],
            [
                'week' => '40',
                'comparison_one' => 'Apple',
                'comparison_one_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a84346.png',
                'comparison_two' => 'Tortoise',
                'comparison_two_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f3a27124.png',
                'comparison_three' => 'Cake',
                'comparison_three_url' => 'https://mandara-files.trogon.info/app/uploads/media/694f6f39bcedc.png',
                'length' => 51.2,
                'weight' => 3462.0,
                'milestone_remarks' => 'Your due date! The baby is fully developed and ready to meet the world. The baby continues to grow and develop, and labor may begin at any time. Congratulations on reaching this milestone!',
            ],
        ];

        foreach ($data as $item) {
            BabySizeComparison::create($item);
        }

        $this->command->info('Baby size comparisons seeded successfully!');
    }
}

