@include('admin.crud.form', [
    'action' => route('admin.assignments.store'),
    'formId' => 'add-assignments-form',
    'submitText' => 'Save Assignments',
    'class' => 'ajax-crud-form',
    'redirect' => route('admin.assignments.index'),
    'fields' => [
        [
            'type' => 'text',
            'name' => 'title',
            'label' => 'Title',
            'placeholder' => 'Enter title',
            'required' => true,
            'col' => 6,
        ],
        [
            'type' => 'select2',
            'name' => 'course_id',
            'label' => 'Course',
            'options' => $courses,
            'placeholder' => 'Select a course...',
            'required' => true,
            'col' => 6,
        ],
        [
            'type' => 'textarea',
            'name' => 'description',
            'label' => 'Description',
            'placeholder' => 'Enter description',
            'required' => true,
            'col' => 12,
        ],
        [
            'type' => 'datetime',
            'name' => 'due_date',
            'label' => 'Due Date',
            'placeholder' => 'Select due date',
            'required' => true,
            'col' => 6,
        ],
        [
            'type' => 'number',
            'name' => 'max_marks',
            'label' => 'Max Marks',
            'placeholder' => 'Enter max marks',
            'required' => true,
            'col' => 6,
        ],
        [
            'type' => 'files',
            'name' => 'assignment_files',
            'label' => 'Assignment Files',
            'presetKey' => 'assignments_files',
            // 'pasteable' => true,
            // 'accept' => 'application/pdf',
            'multiple' => true,
            'col' => 12,
        ],
        [
            'type' => 'select',
            'name' => 'status',
            'label' => 'Status',
            'options' => [
                'active' => 'Active',
                'inactive' => 'Inactive'
            ],
            'col' => 6,
        ],
    ],
])
